### ISSUE TITLE
Refresh Bot

### ISSUE THREAD

**Issue by IIIMathIII** [Tripayou/discordbot-battlemetrics#2]
Hi, it's possible to  do an update to refresh the bot every 1 minute por example and not having to write every time !srvinfo to see the info of the bot.
I don't know if it's possible but i want to know if that is possible!

**Comment by Tripayou** [comment]
Hi,
It's possible and not difficult to do that. Define embed message in thisBot.on('ready') block and use  setInterval() to refresh data and send message ;)
